### ISSUE TITLE
Stuck in magit

### ISSUE THREAD

**Issue by jamesnvc** [magit/transient#121] opened 2021-04-29 14:50 UTC
I've been seeing a strange but transient (no pun intended) issue with magit+transient. 

Sometimes, rarely, when using magit to commit a change, I end up in some strange state where magit keeps acting like there's a transient menu open, preventing me from typing any keys that have actions bound to them. This persists until I quit emacs (which I have to do via the menu bar, since `C-x` gets taken by the transient; even trying to run `M-x` commands doesn't work since typing single characters takes me out of the minibuffer and into a transient).

I'm currently using: `Magit v2.90.1-1233-g3fdf7e0d, Git 2.25.1, Emacs 28.0.50, gnu/linux`, but this happened with magit 3fdf7e0da as well. This has only happened twice to me thus far -- as far as I can tell, it's a result of maybe typing ahead too quickly (i.e. open magit, hitting `c c` and then starting to type a commit message immediately -- but as I said, I'm having a hard time consistently reproducing it.

**Comment by jamesnvc** [comment] 2021-09-27 15:18
I just had this happen again, although I didn't have a chance to grab the lossage. This time it was immediately after building a new Emacs from master & it was doing a bunch of native compilation. I've also stopped using Helm in the interim, so presumably that isn't the issue...

**Comment by tarsius** [comment] 2022-01-01 13:35
I have just pushed a major update that addresses many border-cases and how it does so in this case too. I was never able to reproduce this issue, so I am not sure, but I am closing for now. Please let me know if such an issue occurs again.

**Closed by tarsius** 2022-01-01 13:35 UTC

**Comment by torfjelde** [comment] 2023-01-19 13:49
I'm also currently experiencing the issue and I'm on `transient` 0.3.7 :confused:

I haven't been able to determine what's causing it, but by interacting with the daemon using `emacslient -e` I tried stuff like `transient-quit` and `transient--quit-all` to no avail.

After getting out of the current window I was stuck in (this was related to magit) by calling `kill-buffer`, I then tried just setting `transient--prefix` to `nil` (and I checked: `transient-current-prefix` was also `nil`). But still, once I try hitting certain bindings, e.g. `C-x` because I wanted to see if I could kill a buffer to help, I instead hit `transient-update`. If I try to hit `C-g` I get `transient-quit-one`, etc. So it's basically like I'm still stuck in the `magit` buffer. 

Are there maybe some commands you want me to run from `emacsclient -e` the next time it happens so we can get some debug-info? I tried looking at the transient source but couldn't really identify anything beyond what I already tried.

Btw, thank you for all this awesome work @tarsius; I believe it's my first time making an issue or something on any of your packages but I've been a benefiter for several years now, so thank you!

**Comment by tarsius** [comment] 2023-01-19 15:23
> I'm also currently experiencing the issue and I'm on `transient` 0.3.7 :confused:

Please use the development version. There have been 187 commits since this release, including commits intended to address such issues. I am fairly certain that you cannot get stuck this badly anymore when using that. The worst that could happen is that the popup window gets stuck, but not the key bindings. (And it would be easy to get the window unstuck, simply by entering another transient. But I haven't that seen for quite a while either.)

> Are there maybe some commands you want me to run from `emacsclient -e` the next time it happens so we can get some debug-info?

There is `M-x transient-toggle-debug` now (previously one would have to set a variable manually). But to make use of that one needs a deep understanding of how things are supposed to work.

I plan to make a release very soon, but there is one more serious issue I have to address before then. I actually intend to work on that today, but even if I "finish" it today or tomorrow, I would still have to test it in production for a few days before making a release.

> Btw, thank you for all this awesome work @tarsius; I believe it's my first time making an issue or something on any of your packages but I've been a benefiter for several years now, so thank you!

You are welcome! Always nice to hear from a happy (for the most part :grin:) user.

**Comment by torfjelde** [comment] 2023-01-19 18:42
Awesome! I'm on master now (had to revert `compat.el` back to v28 though to missing def of `compat-alist-get`?) so will se if I run into it again or not:)

**Comment by tarsius** [comment] 2023-02-23 10:51
I've fixed the issue for good (fingers crossed) this February.

I don't use Doom but know that it has a feature that "pins" packages to certain versions and that it is possible for a user to remove that pin or pin to another version. How that is done, I don't know. Please also open an issue in Doom's issue tracker, asking them to update `transient` for all users, mentioning that a serious bug has been fixed since the last pin.
