### ISSUE TITLE
Reached Inconsistent Transient State Detected in cc-isearch-menu

### ISSUE THREAD

**Issue by kickingvegas** [magit/transient#281] opened 2024-03-31 18:06 UTC
# Description

A sequence of key presses will trigger an “Error: Inconsistent Transient State Detected” window in the package `cc-isearch-menu` v1.4.0.

# Environment

-   Transient v1.6.0
-   [cc-isearch-menu](https://github.com/kickingvegas/cc-isearch-menu) v1.4.0
-   Emacs 29.1 (macOS), 29.2 (Linux)

# Steps to Reproduce

1.  In a buffer place the point on any word or symbol.
2.  Press `<f2>` to invoke `cc-isearch-transient-menu`.
3.  Press `t` which invokes `isearch-forward-thing-at-point`.
4.  Press `r` to invoke `isearch-query-replace`.

# Expected Result

The “thing” selected should be set as the query string to be replaced. This would be consistent with the other menu items that allow for pulling in a word (w), symbol (s), or line (l).

# Actual Result

Instead an inconsistent transient state detected error is raised.

Error Window:

    ⛔ Error (transient): Inconsistent transient state detected.
    This should never happen.
    Please open an issue and post the shown command log.
    ⛔ Error (transient): Inconsistent transient state detected.
    This should never happen.
    Please open an issue and post the shown command log.
    ⛔ Error (transient): Inconsistent transient state detected.
    This should never happen.
    Please open an issue and post the shown command log.
    ⛔ Error (transient): Inconsistent transient state detected.
    This should never happen.
    Please open an issue and post the shown command log.
    ⛔ Error (transient): Inconsistent transient state detected.
    This should never happen.
    Please open an issue and post the shown command log.

The command log:

     C-s                    ;; isearch-forward
     <f2>                   ;; cc-isearch-menu-transient
     y                      ;; isearch-yank-kill
     r                      ;; isearch-query-replace
     C-g                    ;; minibuffer-keyboard-quit
     C-a                    ;; back-to-indentation
     C-s                    ;; isearch-forward
     <f2>                   ;; cc-isearch-menu-transient
     t                      ;; isearch-forward-thing-at-point
     r                      ;; isearch-printing-char
    [back]

**Comment by tarsius** [comment] 2024-03-31 22:27
Thanks for the report!

I remember thinking to myself when I saw that someone had created a transient for isearch "I did not expect that to work, I guess I got lucky". But now it turns out I did not.

I don't remember the details, but I think the problem is that, like transient, isearch uses transient keymaps and does unusual things. Each one in isolation works well with other things, but once they meet, things get odd. There is already a lot more compatibility code in transient to deal with isearch, than for any other package.

Fixing that will require quite a bit of work I suspect. I probably won't have the time to do that for a few more weeks.

**Comment by tarsius** [comment] 2024-03-31 22:34
I see, you are the author of `cc-search-menu`; and maybe you want to dig in yourself.

If I remember correctly, the issue is that both transient and isearch need to suspend themselves in certain situations, and when isearch suspends itself and later resumes, then that happens in a way that transient cannot notice, so isearch commands have to be adviced to inform transient that it also has to undergo a state change. Something like that.

**Comment by kickingvegas** [comment] 2024-03-31 22:41
@tarsius Thanks much for the feedback and for making Transient! As it turns out, I’ve run into this issue also in developing Casual, where if I chose to persist a Transient suffix (e.g. `:transient t`), some Calc functions will [trigger](https://github.com/kickingvegas/Casual/blob/ace04facf96e71b097d3ba83f64b1963af4b8f13/lisp/casual-financial.el#L95) the inconsistent state error. These functions take arguments which I’d like to implement as Transient prefix arguments so the user can quickly repeat a command with different prefix values while the menu is still raised. An example where this does work is with the calc depreciation [functions](https://github.com/kickingvegas/Casual/blob/ace04facf96e71b097d3ba83f64b1963af4b8f13/lisp/casual-financial.el#L217).

**Comment by kickingvegas** [comment] 2024-03-31 22:52
On wrapping isearch and Calc commands to inform a Transient of state changes, I'd appreciate any guidance on how to do this. Particularly with Calc, it seems likely that I will wrap all those functions as they do not have docstrings, which renders useless the Transient help feature.

**Comment by kickingvegas** [comment] 2024-04-01 18:15
@tarsius - So it seems that it doesn&rsquo;t matter if I invoke `funcall` or `call-interactively` wrt to triggering the inconsistent state error for Calc. But further investigation shows that calling `calc-hyperbolic` or `calc-inverse` in combination with a `calc-*` function will trigger the error. Looking at both `calc-hyperbolic` and `calc-inverse`, they mess with the keymaps so they look suspect in using them with persisted Transient menus. Further corroborating this is that the depreciation functions don&rsquo;t involve either the hyperbolic or inverse key modifiers.

This looks promising. OTOH, to avoid using the modifiers means refactoring so that I explicitly call the real calc function to do the work. For example with `calc-fin-fv`, I&rsquo;d have to enumerate each call to `calc-enter-result` as a separate function.

    (defun calc-fin-fv ()
      (interactive)
      (calc-slow-wrapper
       (if (calc-is-hyperbolic)
           (calc-enter-result 3 "fvl" (cons 'calcFunc-fvl (calc-top-list-n 3)))
         (let ((n (if (calc-is-option) 4 3)))
           (if (calc-is-inverse)
               (calc-enter-result n "fvb" (cons 'calcFunc-fvb (calc-top-list-n n)))
             (calc-enter-result n "fv" (cons 'calcFunc-fv (calc-top-list-n n))))))))

**Comment by tarsius** [comment] 2024-04-02 02:03
Well... it seems that you got very unlucky trying to add transients to two packages for which it is particularly hard to do so.

> This looks promising. OTOH, to avoid using the modifiers means refactoring so that I explicitly call the real calc function to do the work.

(I haven't looked at any of this very long.) It might indeed be the case that avoiding Calc's own "fancy prefix" functionality entirely and reimplementing its logic using Transient, is your only option.

Out of curiosity, what does this "fancy prefix" thing look like? Does it only add temporary, "modal" key bindings, or does it visualize the available commands, similar (to some extend) to what Transient does?

**Comment by kickingvegas** [comment] 2024-04-02 21:20
@tarsius Looking at the Calc source, it looks like inverse and hyperbolic operations only add modal keybindings, but take no effort to visualize commands like Transient.

    (defun calc-inverse (&optional n)
      (interactive "P")
      (let* ((hyp-flag (if (or
                            (eq major-mode 'calc-keypad-mode)
                            (eq major-mode 'calc-trail-mode))
                           (with-current-buffer calc-main-buffer
                             calc-hyperbolic-flag)
                         calc-hyperbolic-flag))
             (opt-flag (if (or
                            (eq major-mode 'calc-keypad-mode)
                            (eq major-mode 'calc-trail-mode))
                           (with-current-buffer calc-main-buffer
                             calc-option-flag)
                         calc-option-flag))
             (msg
              (cond
               ((and opt-flag hyp-flag) "Option Inverse Hyperbolic...")
               (hyp-flag "Inverse Hyperbolic...")
               (opt-flag "Option Inverse...")
               (t "Inverse..."))))
        (calc-fancy-prefix 'calc-inverse-flag msg n)))
    
    (defun calc-fancy-prefix (flag msg n)
      (let (prefix)
        (calc-wrapper
         (calc-set-command-flag 'keep-flags)
         (calc-set-command-flag 'no-align)
         (setq prefix (set flag (not (symbol-value flag)))
               prefix-arg n)
         (message "%s" (if prefix msg "")))
        (and prefix
             (not calc-is-keypad-press)
             (if (boundp 'overriding-terminal-local-map)
                 (setq overriding-terminal-local-map calc-fancy-prefix-map)
               (let ((event (read-event)))
                 (if (eq (setq last-command-event event) ?\C-u)
                     (universal-argument)
                   (if (or (not (integerp last-command-event))
                           (and (>= last-command-event 0) (< last-command-event ? )
                                (not (memq last-command-event '(?\e)))))
                       (calc-wrapper))  ; clear flags if not a Calc command.
                   (setq last-command-event event)
                   (if (or (not (integerp last-command-event))
                           (eq last-command-event ?-))
                       (calc-unread-command)
                     (digit-argument n))))))))

**Comment by kickingvegas** [comment] 2024-04-05 21:47
Followup on avoiding Calc inverse and hyperbolic modifiers: Made code changes to avoid using them, particularly for the financial functions and it seems like works well with persisted Transient menu behavior. Released with Casual v1.4.0. 
https://github.com/kickingvegas/Casual/pull/124

**Comment by tarsius** [comment] 2024-10-22 14:36
Closing because you found a solution.

Unfortunately following the above link (https://github.com/kickingvegas/Casual/pull/124), doesn't take us to the solution anymore. Having an example of how such a conflict can be resolved might come in hand in the future. Could you please provide a working link to that pull-request or if that has evaporated, to the respective commit. Thanks!

(Are a lot of old topics going to be lost, once you complete the transition to fewer casual packages/repositories, or are you preserving the old repositories? It would probably be best to merely archiving the old repositories, instead of deleting them.)

**Closed by tarsius** 2024-10-22 14:36 UTC

**Comment by kickingvegas** [comment] 2024-10-22 16:31
Due to Casual package consolidation, all links to <https://github.com/kickingvegas/Casual> (redirected to `casual-calc`) created prior to 2024-10-15 are broken. A workaround is to use the direct URL <https://github.com/kickingvegas/casual-calc>.

For reference the broken PR link referenced in this issue is now <https://github.com/kickingvegas/casual-calc/pull/124>

The repositories for superseded Casual packages are to be treated as archives and will not be deleted. Outstanding issues from them will be transferred over to the new Casual repo <https://github.com/kickingvegas/casual> created on 2024-10-15.
