### ISSUE TITLE
Conflict with helm-display-buffer-in-own-frame

### ISSUE THREAD

**Issue by femtogram** [magit/transient#92] opened 2020-07-04 00:35 UTC
Unclear if it is related to https://github.com/magit/transient/issues/34 but I'm running into a problem when using `helm-display-buffer-in-own-frame`.

Here is a basic `init.el` I put together. When commenting one or both of the bottom two lines it functions without issue, but when both lines are uncommented, running `M-x foobar` does not show the `transient` popup. Some guidance for what is going on here or a workaround would be appreciated.

```
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)

(when (not (package-installed-p 'use-package)) (package-refresh-contents) (package-install 'use-package))
(require 'use-package)

(use-package helm
  :ensure t)
(require 'helm-config) ; helm-config is part of the helm package
(helm-mode 1)

(use-package transient
  :ensure t)

(define-suffix-command my/helloworld ()
  (interactive)
  (message "hello world"))

(define-transient-command foobar ()
  "hello world!"
  ["arguments"
   ("-f" "Foo" ("-f" "--foo"))
   ("-b" "Bar" ("-b" "--bar"))]
  [["Hello"
    ("w" "world" my/helloworld)]])

(transient-setup 'foobar nil nil)


; commenting one of the two below will make this function!
; otherwise, hitting `M-x foobar` will break.
(setq helm-display-function 'helm-display-buffer-in-own-frame
        helm-display-buffer-reuse-frame t
        helm-use-undecorated-frame-option t)

(global-set-key (kbd "M-x") 'helm-M-x)
```

Also see attached for a gif of the issue:
![Peek 2020-07-03 20-29](https://user-images.githubusercontent.com/615889/86502016-93158480-bd6c-11ea-9c24-dac1521a1298.gif)

I am running emacs 26.2
Thanks.

**Comment by tarsius** [comment] 2020-07-07 18:47
Let me first rephrase that:

When actually using `helm-M-x` to invoke a transient prefix command and helm is configured to use a separate frame (by setting ...) then and only then does the popup of that transient prefix command fail to come up.

(In other words if not using helm, then it doesn't matter how helm is configured.)

**Comment by tarsius** [comment] 2020-07-07 18:53
The problem is that helm's frame becomes the selected frame, its window becomes the selected window, and its buffer becomes the current buffer. That is wrong. All kinds of things that act on "the current thing" will be start misbehaving if the completion framework temporarily changes what the current thing is.

Now I am not sure why that causes the popup to come up, but I don't really want to investigate this since even if that detail were addressed things would still be fundamentally broken.

I might be wrong about some of this, but I am not motivated to investigate this at this time. My working thesis is "something else does it wrong" after all.

Ps: This should probably be addressed in Helm by restoring the old window configuration *before* invoking the selected command.

**Comment by femtogram** [comment] 2020-07-13 08:35
Oh, of course. I suppose it should have been obvious that that was going on. So I figure if instead I set a key binding this won't be an issue! Thank you for the help.

**Closed** 2020-07-27 16:15 UTC
Labels: elsewhere
