### ISSUE TITLE
error running "magit-branch"

### ISSUE THREAD

**Issue by jtongen1** [magit/transient#93] opened 2020-07-17 22:34 UTC
If my current buffer is in a git repository and I run "magit-branch", I get the following error:

transient--suffix-command: Wrong type argument: transient-suffix, [eieio-class-tag--magit--git-variable 1 nil nil nil nil nil nil nil nil ...], object

If the current buffer is not in a git repository, no error occurs.  I read similar bug reports, but my observed behavior is consistent across multiple emacs processes.

**Comment by kyleam** [comment] 2020-07-18 01:19
Have you tried making sure you have no stale elc files around and reinstalling?

**Comment by jtongen1** [comment] 2020-07-18 03:49
I just uninstalled magit, started a new emacs and verified I have no magit-*** commands, then installed magit via list-packages.  Started a new emacs process and the problem is unchanged.

I'm running on Windows, which sometimes causes different behavior.

Here's my attempt at grabbing a stack trace at the spot I'm guessing the problem is happening:

[trace.txt](https://github.com/magit/transient/files/4941032/trace.txt)

**Comment by tarsius** [comment] 2020-07-18 08:57
You also have to reinstall transient.

**Comment by tarsius** [comment] 2020-07-19 09:32
Duplicate of https://github.com/magit/magit/issues/4154.

**Closed** 2020-07-19 09:32 UTC
Labels: duplicate
