### ISSUE TITLE
Can't revert hunk in commit log buffer by typing `V v`.

### ISSUE THREAD

**Issue by JimMoen** [magit/transient#195] opened 2022-04-06 06:46 UTC
Magit Version: `melpa 20220331.2308`

In magit-revision buffer
(opend from magit buffer by C-m, to view diffs in the specific commit)

Simply type `v` to revert changes is ok

![image](https://user-images.githubusercontent.com/32241529/161911542-0d539f35-b113-4f75-b66f-62d254a9654d.png)

But `V v` seems undefined.

![image](https://user-images.githubusercontent.com/32241529/161911740-00ac5902-1ab7-41d6-90d0-950c610e66cc.png)

**Comment by tarsius** [comment] 2022-04-06 10:49
Thanks for the report! I can reproduce.

This seems to be a regression in `transient`, so I am moving it there. More information follows when I know more.

**Closed** 2022-04-06 11:59 UTC

**Comment by tarsius** [comment] 2022-04-06 12:01
Fixed with 81b2b912de679749a52a4f5faf5fd02b36465431. See that for details.

You will find that, depending on where in the revision buffer the cursor is, `V v` may still not do the same thing as `v`. `V v` is bound to `magit-revert-no-commit`, while `v` is bound to `magit-reverse` iff point is on a file or hunk.
